name: SonarCloud Monorepo Scan
on:
  push:
      branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloudScan1:
    name: SonarCloudScanServer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install tox and any other packages
        working-directory: ./refair-server
        run: pip install tox
      - name: Run tox
        working-directory: ./refair-server
        run: tox -e py
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_SERVER_TOKEN }}
        with:
          projectBaseDir: refair-server/
          
  sonarcloudScan2:
    name: SonarCloudScanClient
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_CLIENT_TOKEN }}
        with:
          projectBaseDir: refair-client/